/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.xbase.lib.util.ReflectExtensions
import org.eclipse.xtext.xbase.testing.CompilationTestHelper
import org.eclipse.xtext.xbase.testing.TemporaryFolder
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith

import static org.junit.Assert.assertEquals

@RunWith(XtextRunner)
@InjectWith(MyDslInjectorProvider)
class MyDslCompilerTest {
	@Rule
	@Inject public TemporaryFolder temporaryFolder
	@Inject extension CompilationTestHelper
	@Inject extension ReflectExtensions
	
	@Test
	def void compileModel() {
		'''
			Hello Xtext {
				val String s = "hello"
				return s.toFirstUpper
			}
		'''.compile[
			assertEquals('''
				package example;
				
				import org.eclipse.xtext.xbase.lib.StringExtensions;
				
				@SuppressWarnings("all")
				public class Xtext {
				  @Override
				  public String toString() {
				    final String s = "hello";
				    return StringExtensions.toFirstUpper(s);
				  }
				}
			'''.toString, getSingleGeneratedCode
			)
			// make sure it compiles in Java
			val obj = it.compiledClass.getDeclaredConstructor().newInstance
			assertEquals("Hello", obj.invoke('toString'))
		]
	}
}
